# Generated by Django 3.2.3 on 2021-05-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210522_1436'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genres',
            field=models.ManyToManyField(to='movies.Genre'),
        ),
    ]
