# Generated by Django 3.2.3 on 2021-05-24 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_auto_20210524_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='liked_user',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
