# Generated by Django 3.2.3 on 2021-05-21 01:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=500)),
                ('backdrop_path', models.CharField(max_length=500)),
                ('release_date', models.DateField()),
                ('director', models.CharField(max_length=50)),
                ('runtime', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('country', models.CharField(max_length=50)),
                ('netflix', models.BooleanField()),
                ('watcha', models.BooleanField()),
                ('wavve', models.BooleanField()),
                ('dislike_users', models.ManyToManyField(related_name='dislike_users', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(to='movies.Genre')),
                ('pick_users', models.ManyToManyField(related_name='pick_users', to=settings.AUTH_USER_MODEL)),
                ('watch_users', models.ManyToManyField(related_name='watch_users', to=settings.AUTH_USER_MODEL)),
                ('wish_users', models.ManyToManyField(related_name='wish_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
