# Generated by Django 3.2.3 on 2021-05-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
