# Generated by Django 3.2.3 on 2021-05-24 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_auto_20210522_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='pick_users',
            field=models.ManyToManyField(related_name='pick_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watch_users',
            field=models.ManyToManyField(related_name='watch_movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='wish_users',
            field=models.ManyToManyField(related_name='wish_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
